---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- harbor-package-install.yaml
secretGenerator:
- name: harbor-packages-values
  namespace: packages
  files:
  - harbor-data-values.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: harbor-packages
